export interface JobPost {
    _id?:any,
    title?: string,
    description?: string,
    location?: string,
    salary?: number,
    type?: string,
    remote?: boolean,
    date?: string,
    employer?: string,
    company?: string,
    applictions?: Array<object>,
    available?: boolean,
    checkSaved?: boolean,
}
